OctopusDeploy/go-octopusdeploy

octopusdeploy/octopusdeploy.go
This extra error handling changed the behavior of the library expected by downstream projects.
=> Fix error handling bug introduced in v1.1.0

octopusdeploy/account.go, octopusdeploy/machines.go
This PR updates the Machines datastructure to allow the creation of Kubernetes deployment targets.
=> Support creating Kubernetes deployment targets

octopusdeploy/octopusdeploy.go
This caused all the tests to fail in the terraform-provider. Need to revisit this after looking into the tests and updating them.
Reverts OctopusDeploy/go-octopusdeploy#20
=> Revert "Show more useful error message on 500 errors"

octopusdeploy/octopusdeploy.go, octopusdeploy/tenant.go
I have followed the pattern from projects.go.
There is however one things i'm slightly currious about: How should tenant variables be handled? It seems to be one big blob that Octopus expects, however the blob is independent in the Octopus api from the tenant resource. 
What i would suggest doing:
Make the variables "sub-resource" be a part of the tenant resource itself, and then we will need to do partial updates to make everything consistent in Terraform? That of-cause means that things in this client library could still be independent. 
This closes #23.
=> Add basic tenant client

octopusdeploy/deployment_action_container.go, octopusdeploy/octopusdeploy.go, octopusdeploy/root_resource.go
The current Pull Request fixes `uriTemplate` ( template path ) for a bunch of OctopusDeploy services.
On Client initialisation, the general API schema is being returned with `Links` list, which is used to set `uriTemplate` for all services. And if `SpaceID` is provided, one more API schema is being returned and **only part** of the services paths are being redeclared with correct values.
The current Pull Request fixes the following behavior:
* SpaceID `Spaces-42` is provided for new Client
* The bunch of resources still have default Space ID `Spaces-1` instead of `Spaces-42` (See screenshot).
* E.g.: Package Service must have `/api/Spaces-42/packages{/id}{?nuGetPackageId,filter,latest,skip,take,includeNotes}` uri template, but it still has …
=> Fixed uriTemplate for a bunch of services for the condition when Space ID is provided

integration/server_status_service_test.go, octopusdeploy/constants_services.go, octopusdeploy/server_status.go, octopusdeploy/server_status_service.go
Implemented serverStatus type and added Get API to serverStatusSevice. Includes simple test.
Refs #47
=> feat: serverStatus and serverStatusService.Get()

octopusdeploy/constants_parameters.go, octopusdeploy/scoped_user_role.go, octopusdeploy/scoped_user_role_service.go, octopusdeploy/scoped_user_role_service_test.go
This adds support for scoped user role 
Implementation is based off of the documentation available in the swagger docs.
Supported:
- Get
- GetById
- Add
- Update
- Delete
Get appears to have limited functionality based on the swagger document and doesn't support any query parameters, so I just left it without a query struct.
=> feat: Add scoped user role support

octopusdeploy/scoped_user_role.go, octopusdeploy/team_service.go
Adds the constructor for new ScopeUserRole structs require for the terraform provider resource.
Adds `GetScopedUserRoles` function to the team service to allow for retrieval of the scoped user roles associated with the team.
=> Scoped User Role Improvements

pkg/projects/project.go
so it can be used against the cli interface NameOrId
=> Project can implement GetName 

pkg/client/octopusdeploy.go, pkg/newclient/httpsession.go, pkg/services/api/api.go, pkg/services/service.go
[sc-31593]
The user-agent string generated at the creation of the client was being overwritten with the default value on each http request.
=> chore: removed redundant setting of user-agent

go.mod, go.sum, pkg/feeds/feed_service.go, test/e2e/feed_service_test.go
Relates to [Updating a helm feed crashes #447](https://github.com/OctopusDeployLabs/terraform-provider-octopusdeploy/issues/447)
=> fix: feeds service

pkg/projects/projects_query.go
before:
`/api/Spaces-1/projects?clonedFromProjectId=&partialName=schedule+script`
after:
`api/Spaces-1/projects?partialName=schedule+script`
=> fix: generated uri can be incorrect for Project Query

go.mod, go.sum, pkg/deployments/deployment_process_test.go, pkg/feeds/feed_service.go
This PR updates the behaviour of the feeds service. Previously, feeds were serialised using the `FeedResource`. This made the API client more difficult to use; users had to know that they needed to perform a type assertion on the outbound feed before using it. This change pushes that (necessary) plumbing back into the function.
The test, `TestDeploymentProcessAsJSON` is included in this PR because of a check that was invalid whilst testing out the Terraform provider.
=> fix: feed update

go.mod, go.sum, pkg/projects/git_persistence_settings.go, pkg/projects/git_persistence_settings_test.go, pkg/projects/project_service.go, test/e2e/project_service_test.go, test/resources/project_test.go
The Git-related persistence settings contain unnecessary information that may be inferred dynamically. This PR changes the state and behaviour of the struct that encompasses this information. The information necessary for the Octopus REST API is inferred dynamically (i.e. at run-time).
=> fix: updated persistence settings

pkg/projects/convert_to_vcs.go, pkg/projects/project_service.go
Fixes the serialization to only pass the initial commit branch if one is needed/specified.
One is needed if the default branch is protected. In this case, if one isn't provided a default will be used.
Relates to OctopusDeployLabs/terraform-provider-octopusdeploy#477
=> Update to only include the initial commit branch if one is specified

pkg/runbooks/runbook.go, pkg/runbooks/runbook_process_service.go
To support https://github.com/OctopusDeployLabs/terraform-provider-octopusdeploy/pull/511 this PR adds an update method to the runbook process service and exposes the `ForcePackageDownload` field on a runbook.
=> Add some additional fields and update functions for runbooks

pkg/machines/kubernetes_endpoint.go
The go library is not serializing the ClusterCertificatePath field for k8s targets. This PR adds that field.
=> Serialise ClusterCertificatePath filed for k8s targets

pkg/client/client_test.go, pkg/client/octopusdeploy.go
This PR adds support for authenticating using an access token, passing it in the `Authorization` header as a bearer token. It forms part of the in-progress work to support connecting to the Octopus API using OpenID Connect and is currently only available internally. When this is released we'll plan to update the readme with instructions on using access tokens.
=> Add support for access token authentication

pkg/client/client_test.go, pkg/client/octopusdeploy.go
Support for authenticating with an access token was introduced in #201. Some feedback on the way this was implemented using a struct directly was put onto a follow up PR in https://github.com/OctopusDeploy/cli/pull/270#discussion_r1319221065 with a nicer approach using some interfaces and functions, to allow better passing of specific credential types and to allow better encapsulation of getting headers. 
This PR implements those changes so that the `NewClientWithCredentials` function now takes in an `ICredential` interface instead of a struct, with implementations of this for `ApiKey` and `AccessToken`. Validation and getting headers have been moved into type specific functions.
=> Refactor credentials to use interface instead of struct

pkg/users/api_key.go, pkg/users/api_key_service.go, test/e2e/api_keys_test.go
[sc-43458]
Fixes https://github.com/OctopusDeploy/Issues/issues/8434
Created different types for the POST response and GET response as the "APIKey" field is different
- Post response:
- GET response:
=> Update APIKey struct

pkg/deployments/deployment_process_service.go
The existing method `GetDeploymentProcessByID` was not inferring the default SpaceID when it was not specified.
=> fix: deployment processes GetByID not inferring spaceID

README.md, pkg/variables/variable_service.go, pkg/variables/variable_service_test.go
[sc-66829]
To support process owners in the terraform provider we need to update the Go Client to handle matching the scope for it, everything else related process owner scope in variables was already implemented
- Updated `MatchesScope` method to match process owners
- Added some basic unit tests for `MatchesScope`
- Fixed broken link in readme
=> chore: Support process scoped variable scope matching

pkg/deployments/deployment_action.go, pkg/gitdependencies/git_dependency.go
[SC-67713]
Octopus supports sourcing scripts from git repositories on some of deployment actions, but currently the go api client which is used by the cli and terraform provider doesn't support the properties required to configure git resource sourcing. 
- Added new git dependency type
- Added new property to deployment action type to use the git dependency type
=> feat: Support git resource sourcing

pkg/deployments/deployment_preview.go, pkg/deployments/deployment_service.go, pkg/resources/display_settings.go, pkg/variables/variable_prompt_options.go, test/resources/display_settings_test.go, uritemplates/links.go
Adds support for fetching deployment previews from the space scoped POST endpoint. This takes an array of DeploymentPreviews (EnvironmentId and TenantId) and returns an array of deploymentPreviews.
Required for change https://github.com/OctopusDeploy/go-octopusdeploy/pull/232. This adds support for only prompting on variable within the deployment scope using the deployments previews endpoint instead of the project variable set.
This is required for a change to the cli, where we currently fetch the variable set and prompt for all variables, irrelevant of the scoping. The change to the CLI will only prompt for variables in that specific set of releases. This is handled by flattening the deployment previews, so if there are multiple environments that contain differently scoped variables they …
=> Add support for deployments previews

pkg/client/octopusdeploy.go, pkg/newclient/httpsession.go
[sc-70983]
```
❯ octopus login --server https://ben-octo.australiaeast.cloudapp.azure.com/octopus --api-key API-apikey
Testing login to Octopus Server: https://ben-octo.australiaeast.cloudapp.azure.com/octopus
Configuring CLI to use API key for Octopus Server: https://ben-octo.australiaeast.cloudapp.azure.com/octopus
Login successful, happy deployments!
❯ octopus space list
NAME     DESCRIPTION  TASK QUEUE
Default               Running
❯ octopus login --server http://localhost:8065 --api-key API-apikey
Testing login to Octopus Server: http://localhost:8065
Configuring CLI to use API key for Octopus Server: http://localhost:8065
Login successful, happy deployments!
❯ octopus space list
NAME      DESCRIPTION  TASK QUEUE
Default                Running
tag sets               Running
```
=> fix: virtual path support 

pkg/feeds/feed_utilities.go, pkg/feeds/feed_utilities_test.go
The issue at https://github.com/OctopusSolutionsEngineering/OctopusRecommendationEngine/issues/7 points to an unexpected feed type being encountered by the library. This PR gracefully returns an error if an unexpected feed type was encountered, and adds a bunch of tests to the feed conversion .
=> Gracefully deal with unexpected feeds and added tests

api/octopus_deploy.json, api/spec.json, pkg/filters/feed_trigger_filter.go, pkg/packages/deployment_action_slug_package.go
There was a breaking [change](https://github.com/OctopusDeploy/OctopusDeploy/pull/24178) to the Project Trigger API for external feed triggers. `DeploymentAction` is now replaced by `DeploymentActionSlug` which means that the Octopus Terraform provider also needs to be updated accordingly.
=> Rename DeploymentAction to DeploymentActionSlug for external feed trigger packages

pkg/triggers/project_trigger_service.go
The call to get a project trigger does not include the space ID, leading to resources not being found. 
For example, this is the error from the terraform provider:
```
Error: Octopus API error: Resource is not found or it doesn't exist in the current space context. Please contact your administrator for more information. []  
with octopusdeploy_project_scheduled_trigger.projecttrigger_octopub___all___yaml_deploy_to_development__apac_, 
on projecttrigger_octopub___all___yaml_deploy_to_development__apac_.tf line 1, in resource "octopusdeploy_project_scheduled_trigger" "projecttrigger_octopub___all___yaml_deploy_to_development__apac_": 
1: resource "octopusdeploy_project_scheduled_trigger" "projecttrigger_octopub___all___yaml_deploy_to_development__apac_" { 
```
This PR uses the standard …
=> Use the standard method for generating a get ID URL

api/octopus_deploy.json, api/spec.json, pkg/deployments/deployment_action.go
The `slug` field is [needed](https://github.com/OctopusDeployLabs/terraform-provider-octopusdeploy/pull/634#discussion_r1588772057) by the Terraform provider as a computed field such that it can be referenced by Terraform resources that depend on it, e.g. External feed triggers.
=> Add slug to DeploymentAction model

pkg/machines/endpoint.go, pkg/machines/endpoint_resource.go, pkg/machines/kubernetes_agent_details.go, pkg/machines/kubernetes_tentacle_endpoint.go, pkg/machines/machine.go, pkg/machines/tentacle_endpoint_configuration.go
To fully be able to manage the Kubernetes agent in an automated environment we need to add a new deployment target endpoint
[Internal Story SC-77238](https://app.shortcut.com/octopusdeploy/story/77238/support-agent-deployment-target-in-terraform-provider)
- Added Kubernetes tentacle endpoint
=> feat: Add kubernetes agent

.github/workflows/integration-tests.yml, pkg/machinepolicies/machine_update_policy.go, pkg/machines/machine_policy_service_test.go, pkg/machines/machine_update_policy.go, tests/docker-compose.yml
Added the new `KubernetesAgentUpdateBehavior` to support the changes added in https://github.com/OctopusDeploy/OctopusDeploy/pull/24499,
Shortcut story: [sc-78687]
=> Add KubernetesAgentUpdateBehavior to MachinePolicy.MachineUpdatePolicy

.github/workflows/release.yml, .goreleaser.yml
v2 of goreleaser has been released in https://github.com/goreleaser/goreleaser/pull/4806 and is now used in https://github.com/goreleaser/goreleaser-action. This caused an issue where we were now passing an invalid argument `--rm-dist` which was deprecated and replaced with `--clean`. 
This PR changes it to pass `--clean` instead and sets v2 in the config.
=> Update to goreleaser v2

internal/utilities.go, pkg/buildinformation/build_information.go, pkg/buildinformation/build_information_query.go, pkg/buildinformation/build_information_service.go, pkg/buildinformation/is_nil.go, pkg/buildinformation/overwrite_mode.go, test/e2e/build_information_test.go, test/resources/build_information_test.go
This PR completes the build information service implementing the following methods:
- `Add`
- `Get`
- `GetAll`
- `GetById`
- `DeleteById`
- `DeleteByIds` (aka Bulk Delete)
[sc-83928]
=> feat: Build information service

pkg/projects/project_service.go
Refactors the following method to no longer use a `ProjectService`
- `GetByName`
- `GetByIdentifier`
[sc-83935]
=> feat: add new functions for getting a project not using a service

pkg/packages/package_service.go
Refactors the following methods to no longer use a `PackageService`
- `GetById`
- `GetAll`
And adds the following methods:
- `Get`
- `DeleteById`
[sc-83932]
=> feat: add new functions for getting a packages not using a service

pkg/projects/project.go, pkg/projects/project_test.go, test/resources/project_test.go
Support for setting the `AllowIgnoreChannelRules` property was added in https://github.com/OctopusDeploy/go-octopusdeploy/pull/253, and was set to a default of false if not supplied. This doesn't match up with how it's treated in Octopus Server when creating/modifying projects, where the property is optional.
This PR fixes that up to match other client libraries by omitting the property if not supplied.
=> fix: Make project AllowIgnoreChannelRules property optional

.github/workflows/integration-tests.yml, pkg/feeds/feeds_query.go
This change adds the Name field to feeds search to support the feeds datasource searching in terraform.
```
data "octopusdeploy_feeds" "foo" {
name      = "foo"
feed_type = "Docker"
skip      = 0
take      = 1
}
data "octopusdeploy_feeds" "bar" {
name = "bar"
feed_type = "Docker"
skip      = 0
take      = 1
}
resource "terraform_data" "feeds" {
input = {
foo = data.octopusdeploy_feeds.foo.feeds[0].id, # Feeds-1
bar = data.octopusdeploy_feeds.bar.feeds[0].id, # also Feeds-1
}
}
output "feeds_out" {
value = resource.terraform_data.feeds
}
```
> 
>  ~ feeds_outy = {
>         id               = "17c8e400-62a6-3c69-c884-5beb7e1c5457"
>       ~ input            = {
>           ~ foo = "Feeds-1689" -> "Feeds-1688"
>             # (1 unchanged attribute hidden)
>         }
>       ~ output …
=> fix: Add feed name to search functionality

pkg/machines/worker_service.go, pkg/workers/worker_service.go, test/e2e/worker_service_test.go
The current `worker_service` is still using the 'old' client which does not utilise the `SpaceID` on the Worker resource. This means that the worker_service cannot be used in situations where the spaceId is not already set on the base client itself. An example of such a situation is when you want to create the space and worker resource in the same invocation of `terraform apply`. The spaceId cannot be known ahead of time, and hence cannot be set on the Terraform provider config in advance. The current code then creates a bug as the optional SpaceID field on the Worker suggests that the service supports space delimited operations, whereas in reality the operations fallback to the default space.
Needed for https://github.com/OctopusDeployLabs/terraform-provider-octopusdeploy/pull/655
Copies …
=> Add space delimited CRUD operations to Workers using the new client

pkg/releases/create_release_v1.go
Adds SDK support for changing the git refs for Git resources when creating a release
Shortcut story: [sc-69100]
Now the feature toggle is at 100% rollout, this can be merged
=> Add support for changing git resource refs when creating a release

pkg/deployments/deployment_process_template.go, pkg/releases/release_template_git_resource.go
Adds the `GitResources` field to the `DeploymentProcessTemplate` struct.
This is a list of `ReleaseTemplateGitResources`, representing any git resources associated with the deployment process actions
=> Add GitResources to DeploymentProcessTemplate

pkg/feeds/feed_utilities.go, pkg/feeds/feed_utilities_test.go
Add mapping from feed to resource for OCI Registry feed
Updating OCI Registry feed were failing with error below, because of missing mapping from feed object to API Resource for this particular feed type.
```
Error: unable to update OCI Registry feed
with octopusdeploy_oci_registry_feed.registry_42,
on main.tf line 25, in resource "octopusdeploy_oci_registry_feed" "registry_42":
25: resource "octopusdeploy_oci_registry_feed" "registry_42" {│
Octopus API error: There was a problem with your request. [The FeedUri field is required. The Feed URL must be a valid URI]
```
=> Fix OCI Registry feed update

pkg/client/octopusdeploy.go
The Go Client has a factory method called `NewClientForTool` which used to instantiate the client with a default useragent string that includes the provided `requestingTool` value, so that we can disambiguate between client consumers in our logs. The plumbing of the `requestingTool` parameter here got broken accidentally during a refactor.
This PR restores that plumbing.
=> fix: requestingtool not plumbed through to useragent in client creation

pkg/tenants/tenant.go, pkg/tenants/tenant_service.go, pkg/tenants/tenants_query.go, test/e2e/tenant_service_test.go
Adds the `isDisabled` field to a tenant and update e2e tests to ensure field is set. [#project-disabling-tenants
](https://octopusdeploy.slack.com/archives/C07VBST79AL)
=> feat: Add isDisabled field to tenant

pkg/client/octopusdeploy.go, pkg/deploymentfreezes/deploymentfreeze.go, pkg/deploymentfreezes/deploymentfreeze_query.go, pkg/deploymentfreezes/deploymentfreeze_service_test.go, pkg/deploymentfreezes/deploymentfreezes_service.go
=> feat: deployment freezes

pkg/deploymentfreezes/deploymentfreeze_query.go, pkg/deploymentfreezes/deploymentfreezes_service.go
=> fix: added Partial Name and Status to deployment freeze query

pkg/triggers/project_trigger.go, pkg/triggers/project_trigger_test.go
When creating a new project trigger, description is passed to the function but is not used to set the value, this value will now be set
=> Use description during NewProjectTrigger creation

pkg/triggers/project_trigger_service.go, test/e2e/project_trigger_test.go
[SC-97304]
Use the new client for project triggers to allow scoping by space ID in terraform when the resource differs from the provider
=> Use the new client for project triggers

pkg/deploymentfreezes/deploymentfreeze.go, test/e2e/build_information_test.go, test/e2e/deployment_freeze_service_test.go
added daily recurring schedule test
this is only marked as a chore even though it is technically a breaking change, the feature is not public in server yet.
[sc-99541]
=> chore: renamed freeze recurring schedule types to align with server

.github/workflows/integration-tests.yml, pkg/scriptmodules/script_module_service.go, test/e2e/script_module_service_test.go
When retrieving all script modules we do not populate the script syntax and body like we do when retrieving a single script module, this PR updates the logic to populate these fields when listing all script modules.
[sc-103152]
=> fix: populate script syntax and body when retrieving all script modules

pkg/configuration/feature_toggle_configuration.go, pkg/configuration/feature_toggle_configuration_service.go, pkg/newclient/crud.go, pkg/newclient/httpsession.go, pkg/tenants/tenant_service.go, pkg/variables/tenant_common_variable.go, pkg/variables/tenant_project_variable.go, pkg/variables/tenant_variable_scope.go
[SC-93476] [SC-101710]
New tenant variables endpoints have been added to Octopus Server to allow multi-environment scoping for Common and Project Tenant Variables. This PR adds support for the new endpoints, and for the feature toggles endpoint to allow verification of whether the endpoints are available:
- `/api/{SpaceId}/tenants/{TenantId}/commonvariables` (GET/PUT/POST)
- `/api/{SpaceId}/tenants/{TenantId}/projectvariables` (GET/PUT/POST)
Feature toggles can be queried by name - both of the above endpoints are under `CommonVariableScopingFeatureToggle`.
=> Add support for new tenant variables endpoints with environment scoping

pkg/configuration/feature_toggle_configuration_service.go, pkg/newclient/crud.go, pkg/tenants/tenant_service.go, pkg/variables/tenant_common_variable.go, pkg/variables/tenant_project_variable.go
[SC-103994]
Updates to the `/api/tenants/Tenants-1/commonvariables` and `/api/tenants/Tenants-1/projectvariables` endpoints in Octopus Server allow including an optional `IncludeMissingProjectVariables` or `IncludeMissingCommonVariables` query parameter. When the parameter is true, the server will include any missing or default variables as a separate list in the response. Missing and default variables are required by the CLI for output
Request: `/api/tenants/Tenants-1/commonvariables`
```
{
"TenantId": "Tenants-1",
"CommonVariables": [
{
"Id": "TenantVariables-408",
"LibraryVariableSetId": "LibraryVariableSets-41",
"LibraryVariableSetName": "missing set 1",
"TemplateId": "eb285bce-d20d-4136-877c-399c8572115a",
"Template": {
"Id": "eb285bce-d20d-4136-877c-399c8572115a",
"Name": "missing …
```
=> Get missing project and common variables

pkg/variables/variable_service.go
Old variable scope compare is not strict enough and will return true if anything in the scope matches. The new function is more strict making it more suitable in situations where a direct match is needed.
=> feat: strict variable scope compare

pkg/client/root_service.go
The cli tests are failing:
```
FAIL pkg/apiclient.TestClient_GetSystemClient/GetSystemClient_returns_the_client (0.00s)
fakeoctopusserver.go:151: 
Error Trace:	/home/runner/work/cli/cli/test/testutil/fakeoctopusserver.go:151
/home/runner/work/cli/cli/pkg/apiclient/apiclient_test.go:34
Error:      	Not equal: 
expected: "/api/"
actual  : "/api"
Diff:
--- Expected
+++ Actual
@@ -1 +1 @@
-/api/
+/api
Test:       	TestClient_GetSystemClient/GetSystemClient_returns_the_client
```
This PR changes the path to the path expected by the cli tests.
=> chore: change response to match cli integration tests

pkg/spaces/space.go
This is a recreation of #317 due to limitations around secrets in our build pipelines. Thank you to @katrinajaneczko for the original contribution
> Issue: https://github.com/OctopusDeploy/go-octopusdeploy/issues/316
> Updated the maximum character limit for a space name/slug in `go-octopusdeploy` from 20 to 50, aligning with the update made in release `2025.2.1408` of Octopus (see: https://github.com/OctopusDeploy/Issues/issues/9272).
=> feat: update max char limit for space name to 50

internal/validation.go, pkg/core/sensitive_value.go, pkg/feeds/azure_container_registry.go, pkg/feeds/google_container_registry.go
[sc-108576]
Fixes a bug introduced in https://github.com/OctopusDeploy/go-octopusdeploy/pull/324.
A misunderstanding of how sensitive values are handled was causing unexpected errors when creating ACR and GCR resources using password authentication. This was discovered while testing ACR/GCR creation via the terraform provider.
=> Fix bad password validation

pkg/feeds/feed_utilities.go
[sc-108604]
Fixes a bug introduced in https://github.com/OctopusDeploy/go-octopusdeploy/pull/322 and duplicated in https://github.com/OctopusDeploy/go-octopusdeploy/pull/324.
As part of the work adding OIDC to ACR feeds, ACR resources were decoupled from docker feed resources.
Some field mappings were not migrated to the new `ToFeed` conversion logic, causing errors handling `APIVersion`, `FeedURI` and `RegistryPath` attributes. This oversight was also duplicated in the GCR OIDC changes.
=> Fix missing docker registry field mappings for ACR and GCR feed conversions

pkg/projects/project.go, pkg/projects/project_test.go, test/resources/project_test.go
In https://github.com/OctopusDeploy/OctopusDeploy/pull/33075 we added a new project setting to alter the behaviour of how [Kubernetes Live Object Status](https://octopus.com/docs/kubernetes/live-object-status) is displayed on dashboards.
This change adds the field to this client.
=> Add live status dashboard option to Project

README.md, pkg/machinepolicies/machine_package_cache_retention_policy.go, pkg/machinepolicies/machine_policy.go, pkg/machines/machine_package-cache_retention_policy.go, pkg/machines/machine_policy.go, pkg/machines/machine_policy_service_test.go
The machine policy has a new field for package cache retention settings, which enables configurable package cache on deployment targets and workers.
This PR adds the new field to the Go client.
[sc-112057]
Related: https://github.com/OctopusDeploy/Issues/issues/9421
=> Add package cache retention setting to machine policy

pkg/feeds/built_in_feed.go, pkg/feeds/feed_resource.go, pkg/feeds/feed_utilities.go, pkg/feeds/feed_utilities_test.go, test/resources/feed_utilities_test.go
[On an octopus server PR](https://github.com/OctopusDeploy/OctopusDeploy/pull/33384) a new property was added to enable users to delete packages while still saving releases - `DeletePackagesAssociatedWithReleases`.
Here we add the`DeletePackagesAssociatedWithReleases` to the go client as well. 
[[sc-111133]](https://app.shortcut.com/octopusdeploy/story/111133/are-there-are-any-clients-that-can-configure-the-built-in-feed)
=> add DeletePackagesAssociatedWithReleases property

pkg/credentials/resource.go, pkg/credentials/resource_test.go, test/e2e/git_credential_service_test.go
[sc-112803]
Part of [#project-argo-cd-in-octopus](https://octopusdeploy.slack.com/archives/C08QKUX0LHW)
Updating the client to add the new repository restriction property. [Corresponding server changes here](https://github.com/OctopusDeploy/OctopusDeploy/commit/0bf2e63b5e114cfd5dd8fa8f9a8c8fd5425fb204#diff-98ba59e06c23b45f71e7e0471869dc3f402b7d107545bf4e5ef6cd9479417996).
Related to: https://github.com/OctopusDeploy/Issues/issues/9471
=> Add support for Git Credential Repository Restrictions

pkg/feeds/aws_elastic_container_registry.go, pkg/feeds/feed_resource.go, pkg/feeds/feed_utilities.go, pkg/feeds/google_container_registry.go, pkg/feeds/oidc_authentication.go, pkg/feeds/oidc_authentication_test.go, pkg/spaces/space.go
When updating ACR, GCR and ECS feeds the OidcAuthentication property is not being bound on the server side modify calls. This happens because the FeedResource properties `AzureContainerRegistryOidcAuthentication`, `ElasticContainerRegistryOidcAuthentication` and `GoogleContainerRegistryOidcAuthentication` do not match the server side values. This change consolidates these into a single property OidcAuthentication which has a type property to discriminate on. The JSON unmarshalling here isn't pretty but works, it determines the OidcAuthentication type based on the available properties, in this case the properties are always available, and we're just checking it's there the value itself is not required.
Related to - https://github.com/OctopusDeploy/terraform-provider-octopusdeploy/pull/40/fi …
=> Consolidate the OidcAuthentication properties on FeedResource into a single property

pkg/observability/container_logs.go, pkg/observability/container_logs_service.go, pkg/observability/container_logs_test.go
This PR adds support for the BeginContainerLogsSession API
**Testing evidence:**
Using a local go client:
```
2. Testing with New Client (BeginContainerLogsSessionWithClient)...
New client created successfully
Making API call with new client, command: &{SpaceID:Spaces-1 ProjectID:Projects-101 EnvironmentID:Environments-3 TenantID:<nil> MachineID:Machines-61 DesiredOrKubernetesMonitoredResourceID:0992a29a-5070-4314-9b34-034a81200dc9 PodName:test-api-deploy-7bb97cf98-d7rb6 ContainerName:test-nginx ShowPreviousContainer:false}
API call succeeded: &{SessionID:ed557d12-c676-4b1e-b4ac-154c75abefb7 Error:<nil>}
Response - Full object (JSON):
{
"sessionId": "ed557d12-c676-4b1e-b4ac-154c75abefb7"
}
```
Matches actual request and response structure on UI:
Request payload:
``` …
```
=> Add support for BeginContainerLogsSession

pkg/observability/resource_events.go, pkg/observability/resource_events_service.go, pkg/observability/resource_events_test.go
This PR adds support for the BeginResourceEventsSession API
**Testing evidence**
Actual UI:
Request:
```
{
"ProjectId": "Projects-101",
"EnvironmentId": "Environments-3",
"MachineId": "Machines-61",
"DesiredOrKubernetesMonitoredResourceId": "98dca12e-eb95-4757-bac9-d54018e75310"
}
```
Response:
```
{
"SessionId": "dbc67366-b02f-4148-8aae-da335325e178"
}
```
Test go client:
```
2. Testing with New Client (BeginResourceEventsSessionWithClient)...
New client created successfully
Making API call with new client, request: &{SpaceID:Spaces-1 ProjectID:Projects-101 EnvironmentID:Environments-3 TenantID:<nil> MachineID:Machines-61 DesiredOrKubernetesMonitoredResourceID:98dca12e-eb95-4757-bac9-d54018e75310}
API call succeeded: &{SessionID:79861439-124e-46f4-951a-3e527af03e41}
Response - Full …
```
=> Add support for BeginResourceEventsSession API

pkg/actiontemplates/action_template_service.go
This PR adds a `Get` function to the step template service to allow templates to be searched. This is required to implement a proper data source in the Terraform provider to look up existing step templates.
=> Add step template Get function

pkg/channels/channel.go, pkg/channels/channel_custom_field_definition.go, pkg/releases/create_release_v1.go, pkg/releases/release.go, test/e2e/channel_service_test.go
We are adding support for Custom Fields on releases as part of the new Ephemeral Environments feature coming to Octopus. This will allow custom key/value data to be stored on a release and used as part of naming automatically created ephemeral environments from releases. Channels can define which custom fields are required for releases created.
Adds new properties to channel and release for custom fields.
[sc-113197]
=> feat: Add support for custom fields on releases

pkg/channels/channel.go, pkg/channels/channel_service_test.go, pkg/channels/channel_type.go, test/e2e/channel_service_test.go
Ephemeral Environments has introduced a new type of channel called an Ephemeral Environment Channel. This change adds this new channel type, along with its new fields (EphemeralEnvironmentNameTemplate and ParentEnvironmentID) to the channel.
[sc-122355]
=> feat: Add Ephemeral Environment Fields to Channel

pkg/environments/parentenvironments/parent_environment.go, pkg/environments/parentenvironments/parent_environment_service.go
Ephemeral environments have introduced the concept of a parent environment. This environment will be linked to an ephemeral environment so that it can be used to set for example, variables on the parent environment to be used for the ephemeral environment.
This change adds the parent environment model.
[sc-122355]
=> Add Parent Environment
