OctopusDeploy/go-octopusdeploy

- integration/tenant_test.go
- octopusdeploy/octopusdeploy.go
- octopusdeploy/tenant.go
Add support for tenants + some tests
> Add support for tenants

- octopusdeploy/common_models.go
- octopusdeploy/octopusdeploy.go
- octopusdeploy/user.go
Added user configurations in for creating/updating/deleting users. Still working through a creation bug, but nothing broken from it.
> Feature user creation

- octopusdeploy/account.go
Validation additions to point to the enums for UsernamePassword and SshKeyPair
> Feature account resource validation

- octopusdeploy/account_type.go
- octopusdeploy/account_type_enum.go
Fixes #31 by adding the Token account type to the enumeration
> Added Token account type to enumeration

- octopusdeploy/octopusdeploy.go
- octopusdeploy/server_status_service.go
> Fixed typo for type, serverStatusService

- octopusdeploy/channel_rule.go
> fix: updated action packages to serialize properly

- integration/variables_test.go
- octopusdeploy/variable.go
- octopusdeploy/variable_scope.go
- octopusdeploy/variable_scope_test.go
- octopusdeploy/variable_service.go
> Fix variable structure and serialization

- octopusdeploy/team.go
> fix: updated serialization tag for property

- examples/runbook_snapshots/create_runbook_snapshot.go
- integration/runbook_service_test.go
- integration/runbook_snapshot_service_test.go
- octopusdeploy/constants_parameters.go
- octopusdeploy/release_template_package.go
- octopusdeploy/runbook.go
- octopusdeploy/runbook_service.go
- octopusdeploy/runbook_snapshot.go
- octopusdeploy/runbook_snapshot_service.go
- octopusdeploy/runbook_snapshot_service_test.go
- octopusdeploy/runbook_snapshot_template.go
> Enhancement: Runbook snapshot support

- pkg/releases/create_release_v1.go
fixes https://github.com/OctopusDeploy/go-octopusdeploy/issues/129
> fix: CreateReleaseV1 specified channel incorrectly

- pkg/lifecycles/lifecycle_service.go
- pkg/lifecycles/lifecycle_service_test.go
- pkg/projectgroups/project_group_service.go
- pkg/projectgroups/project_group_service_test.go
> feat: add GetByName and GetByIdOrName to project groups and lifecycles

- pkg/projects/project_service.go
- pkg/tenants/tenant_service.go
[sc-27715]
Relates to https://github.com/OctopusDeploy/cli/pull/119
> feat: Tenant GetByName, GetByIdentifier

- pkg/workerpools/worker_pool.go
- pkg/workerpools/worker_pool_service.go
- test/e2e/worker_pool_service_test.go
- test/e2e/worker_service_test.go
> fix: update Worker Pool GetAll to return a summary type

- pkg/accounts/azure/azurewebapp.go
- pkg/constants/constants_links.go
These functions are written in a different style and are not attached to a *Service, but require the client to be passed in
> added functions for listing websites and slots for an azure account

- pkg/machines/listening_tentacle_endpoint_test.go
- pkg/machines/machine_service.go
- pkg/machines/tentacle_version_details.go
- pkg/machines/worker_test.go
- pkg/proxies/proxy_service.go
- pkg/workerpools/worker_pool.go
fix!: tentacle version details version field
feat: get proxy by id
> feat: machine getbyidentifier

- pkg/client/client_test.go
- pkg/client/octopusdeploy.go
- pkg/client/test_helpers.go
- pkg/services/api/api.go
- pkg/services/api/automation_environment_provider.go
- pkg/services/api/automation_environment_provider_test.go
- pkg/services/api/environment.go
> support for automation environment and tool data on useragent

- pkg/machines/worker_service.go
- pkg/workerpools/worker_pool.go
- pkg/workerpools/worker_pool_service.go
> feat: Worker Pool GetByName and GetByIdentifier

- pkg/spaces/space.go
- test/e2e/space_service_test.go
> chore: always send IsDefault flag value with space post

- pkg/workerpools/worker_pool_service.go
> feat: list workers for a worker pool

- .github/workflows/integration-tests.yml
- .github/workflows/skip-test.yml
- pkg/services/service.go
- pkg/spaces/spaces_query.go
- pkg/users/api_key_service_test.go
- test/e2e/feed_service_test.go
fixes https://github.com/OctopusDeploy/go-octopusdeploy/issues/87
> fix: removed incorrect query parameter

- pkg/machines/kubernetes_endpoint.go
The library is not current deserialising k8s pods auth. This PR adds that ability.
> Fixed an issue where pod auth is not deserialised properly

- pkg/deployments/deployment_preview.go
Add new struct commands for test fixtures.
> Chore: Add deployment preview new struct functions for tests

- pkg/feeds/feed_resource.go
- pkg/feeds/feed_types.go
- pkg/feeds/feed_utilities.go
- pkg/feeds/s3_bucket.go
- test/e2e/feed_service_test.go
Personal version of funkbunker's PR to test actions
> feat: add AWS S3 feed type

- pkg/channels/channel.go
- pkg/channels/channel_git_resource_rule.go
- pkg/gitdependencies/deployment_action_git_dependency.go
- pkg/projects/project.go
- pkg/projects/project_test.go
- test/e2e/channel_service_test.go
- test/e2e/project_service_test.go
- test/resources/project_test.go
This PR adds new properties to channels and projects for the upcoming Git protection rules feature.
[sc-83091]
> feat: Add Git protection rules to channels

- .github/workflows/integration-tests.yml
Hopefully will force a re-run to unblock `main`
> Bump actions/checkout

- pkg/defects/defect.go
- pkg/defects/defect_service.go
- pkg/defects/defect_test.go
This PR adds a new service to manage release defects:
- `GetAll`
- `Create`
- `Resolve`
[sc-87084]
> feat: add release defects service

- pkg/actiontemplates/action_template_service.go
- test/e2e/action_template_service_test.go
Moving parts of action template to work with new client for support with terraform provider and space Id not being locked to the client.
> feat: partial support for action templates in new client

- pkg/lifecycles/lifecycle_test.go
- pkg/lifecycles/phase.go
support for priority lifecycle
> feat: isPriorityPhase on lifecycle phases.

- pkg/feeds/feed_types.go
- pkg/feeds/feed_utilities.go
- pkg/feeds/feed_utilities_test.go
- pkg/feeds/oci_registry_feed.go
Allows to create or query feeds of type OCI Registry
> Add support for OCI Registry feeds

- pkg/releases/release_template_package.go
This PR adds `FixedVersion` to `ReleaseTemplatePackage` to match the new fixed package versioning feature that is rolling out through Octopus Cloud.
> feat: Adds FixedVersion to template packages

- pkg/proxies/proxy_service.go
> feat: full machine proxy support

- pkg/serviceaccounts/oidc_identities.go
- pkg/serviceaccounts/service_accounts.go
Support for service account OIDC identities
> feat: support service account OIDC identities

- pkg/deploymentfreezes/deploymentfreeze.go
- pkg/deploymentfreezes/deploymentfreeze_query.go
- pkg/deploymentfreezes/deploymentfreezes_service.go
> fix: small fixes for deployment freeze API calls

- pkg/accounts/account.go
- pkg/accounts/account_resource.go
- pkg/accounts/account_types.go
- pkg/accounts/account_utilities.go
- pkg/accounts/accounts.go
- pkg/accounts/generic_oidc_account.go
- pkg/accounts/generic_oidc_account_test.go
Adds ability to create and get a generic oidc account.
[sc-98285]
> feat: Add generic oidc account

- pkg/variables/tenant_common_variable.go
- pkg/variables/tenant_project_variable.go
I couldn't easily "rename" via my IDE, so I'm not super confident there aren't more things. But it builds....
> chore: rename properties to match API

- pkg/deploymentfreezes/deploymentfreeze.go
> Add support for project deployment freezes

- pkg/deploymentfreezes/deploymentfreeze.go
Update recurring schedule model to support a UTC offset.
[sc-105206]
> Add support for specifying users utc offset on recurring schedule

- pkg/channels/channel_service.go
- pkg/channels/query.go
Add filter by projectID to channel.
> Add filter by projectID to channel

- pkg/feeds/azure_container_registry.go
- pkg/feeds/docker_container_registry.go
- pkg/feeds/feed_resource.go
- pkg/feeds/feed_types.go
- pkg/feeds/feed_utilities.go
[sc-107469]
See equivalent changes for ECR resources: https://github.com/OctopusDeploy/go-octopusdeploy/pull/321.
> Extend ACR feed resource to support OIDC properties

- internal/validation.go
- pkg/core/sensitive_value.go
- pkg/feeds/azure_container_registry.go
- pkg/feeds/docker_container_registry.go
- pkg/feeds/feed_resource.go
- pkg/feeds/feed_types.go
- pkg/feeds/feed_utilities.go
- pkg/feeds/google_container_registry.go
[sc-107470]
See equivalent changes for:
- ACR: https://github.com/OctopusDeploy/go-octopusdeploy/pull/322.
- ECR: https://github.com/OctopusDeploy/go-octopusdeploy/pull/321.
> Extend GCR feed resource to support OIDC properties

- pkg/actiontemplates/action_template.go
Add git dependencies to action template
> Add git dependencies to action template

- examples/teams/create_team.go
- pkg/teams/team_service.go
- test/e2e/team_service_test.go
[sc-84347]
Prerequisite work to migrating team resource to terraform plugin framework.
> Add team service new client functions

- pkg/tasks/task_service.go
Add function for cancelling a server task by id
[sc-108942]
> Add Task Cancel

- pkg/releases/missing_package_info.go
- pkg/releases/release_service.go
- uritemplates/links.go
Adds missing packages for release to the client.
[sc-111471]
[sc-110366]
> feat: Add missing packages for release

- pkg/projectgroups/project_group.go
> feat: add slug support to project group

- pkg/core/retention_period.go
- pkg/lifecycles/lifecycle.go
- pkg/lifecycles/lifecycle_test.go
- pkg/lifecycles/phase.go
- test/e2e/lifecycle_service_test.go
Add support for setting space default on lifecycle retention policies
[sc-118376]
> Centralised Retention - Add support for setting space default on lifecycle retention policies
